package user

import "errors"

// errors
var (
	ErrZeroUserID                = errors.New("user id is zero")
	ErrNoInputData               = errors.New("no input data")
	ErrNilManager                = errors.New("user manager is nil")
	ErrUserExists                = errors.New("user already exists")
	ErrNilUser                   = errors.New("user is nil")
	ErrNilUserStore              = errors.New("user store is nil")
	ErrUsernameTaken             = errors.New("username is already taken")
	ErrEmptyEmailAddr            = errors.New("empty email address")
	ErrDuplicateEmailAddr        = errors.New("duplicate email address")
	ErrEmptyPhoneNumber          = errors.New("empty phone number")
	ErrDuplicatePhoneNumber      = errors.New("duplicate phone number")
	ErrEmailTaken                = errors.New("email is already taken")
	ErrNilEmail                  = errors.New("email is nil")
	ErrNilPhone                  = errors.New("phone is nil")
	ErrDuplicatePhone            = errors.New("duplicate phone")
	ErrPhoneNotFound             = errors.New("phone not found")
	ErrIndexNotFound             = errors.New("index not found")
	ErrRelationNotFound          = errors.New("relation not found")
	ErrUserNotFound              = errors.New("user not found")
	ErrEmailNotFound             = errors.New("email not found")
	ErrUnknownUser               = errors.New("unknown user")
	ErrNilContainer              = errors.New("container is nil")
	ErrShortPassword             = errors.New("password is too short")
	ErrLongPassword              = errors.New("password is too long")
	ErrUnsafePassword            = errors.New("password is too unsafe")
	ErrNilUserIndex              = errors.New("user index is nil")
	ErrObjectIsNew               = errors.New("object is new")
	ErrObjectIsNotNew            = errors.New("object is not new")
	ErrUnknownIndex              = errors.New("unknown index")
	ErrInsufficientDataToHashKey = errors.New("insufficient data to hash a key")
	ErrUserAlreadyConfirmed      = errors.New("user is already confirmed")
	ErrNilPasswordManager        = errors.New("password manager is nil")
	ErrUserPasswordNotEligible   = errors.New("user is not eligible for password assignment")
	ErrNilProfile                = errors.New("profile is nil")
	ErrDuplicateProfile          = errors.New("duplicate profile")
	ErrProfileNotFound           = errors.New("profile not found")
	ErrNoParentPolicy            = errors.New("no parent access policy")
	ErrNoPolicyBackup            = errors.New("no policy backup")
	ErrNoParentGroup             = errors.New("no parent group")
	ErrZeroGroupID               = errors.New("role group id is zero")
	ErrZeroRoleID                = errors.New("role id is zero")
	ErrZeroAssignorID            = errors.New("assignor id is zero")
	ErrZeroAssigneeID            = errors.New("assignee id is zero")
	ErrInvalidName               = errors.New("invalid name")
	ErrInvalidObjectType         = errors.New("invalid object type")
	ErrZeroObjectID              = errors.New("object id is zero")
	ErrInvalidGroupKey           = errors.New("invalid group key")
	ErrInvalidGroupName          = errors.New("invalid group name")
	ErrEmptyGroupKey             = errors.New("group key is empty")
)
