package user

import "errors"

// errors
var (
	ErrZeroUserID                      = errors.New("user id is zero")
	ErrNoInputData                     = errors.New("no input data")
	ErrNilManager                      = errors.New("user manager is nil")
	ErrUserExists                      = errors.New("user already exists")
	ErrNilUser                         = errors.New("user is nil")
	ErrNilUserStore                    = errors.New("user store is nil")
	ErrUsernameTaken                   = errors.New("username is already taken")
	ErrEmptyEmailAddr                  = errors.New("empty email address")
	ErrDuplicateEmailAddr              = errors.New("duplicate email address")
	ErrEmptyPhoneNumber                = errors.New("empty phone number")
	ErrDuplicatePhoneNumber            = errors.New("duplicate phone number")
	ErrEmailTaken                      = errors.New("email is already taken")
	ErrDuplicatePhone                  = errors.New("duplicate phone")
	ErrPhoneNotFound                   = errors.New("phone not found")
	ErrUserNotFound                    = errors.New("user not found")
	ErrEmailNotFound                   = errors.New("email not found")
	ErrUnknownUser                     = errors.New("unknown user")
	ErrInsufficientDataToHashKey       = errors.New("insufficient data to hash a key")
	ErrUserAlreadyConfirmed            = errors.New("user is already confirmed")
	ErrNilPasswordManager              = errors.New("password manager is nil")
	ErrUserPasswordNotEligible         = errors.New("user is not eligible for password assignment")
	ErrDuplicateProfile                = errors.New("duplicate profile")
	ErrProfileNotFound                 = errors.New("profile not found")
	ErrNoParentPolicy                  = errors.New("no parent accesspolicy policy")
	ErrNoPolicyBackup                  = errors.New("no policy backup")
	ErrNoParentGroup                   = errors.New("no parent group")
	ErrZeroGroupID                     = errors.New("role group id is zero")
	ErrZeroRoleID                      = errors.New("role id is zero")
	ErrZeroAssignorID                  = errors.New("assignor id is zero")
	ErrZeroAssigneeID                  = errors.New("assignee id is zero")
	ErrNothingChanged                  = errors.New("nothing has changed")
	ErrZeroID                          = errors.New("id is zero")
	ErrNonZeroID                       = errors.New("id is non-zero")
	ErrInvalidSuspensionExpirationTime = errors.New("suspension expiration time is invalid")
	ErrUserAlreadySuspended            = errors.New("user is already suspended")
)
